### ISSUE TITLE
Warnings on HA version 2022.2

### ISSUE THREAD

**Issue by HepoH3** [ClusterM/skykettle-ha#6] opened 2022-02-10 14:24 UTC
After updating core following warnings are shown:

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 89: self._child.sendline(f"connect")

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 93: self._child.sendline("char-write-cmd 0x000c 0100")

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 60: self._child.sendline(data)

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 102: self._child.sendline(f"disconnect")

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 120: self._child.terminate(force=True)

**Comment by ClusterM** [comment] 2022-02-10 14:25
Already fixed, check latest commit.

**Comment by HepoH3** [comment] 2022-02-10 14:32
> Already fixed, check latest commit.

Got you. I'll switch to master branch.

**Comment by ClusterM** [comment] 2022-02-10 16:25
I'll check it.

**Comment by ClusterM** [comment] 2022-02-10 16:42
Hm. I'll check it.

**Comment by ClusterM** [comment] 2022-02-10 17:22
Sorry, I'm an idiot. Seems like I really fixed it now.

**Comment by ClusterM** [comment] 2022-02-10 21:08
Please try commit 5ce7163685ca2bb2cb6b7f97edafdbbff481c9fc

**Comment by HepoH3** [comment] 2022-02-11 05:06
Found another one:

> Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 133: self._child.terminate(force=True)

**Comment by HepoH3** [comment] 2022-02-11 08:43
I think we need separate brunch for blocking calls which eventually will be merged into master with squashed commits.

**Comment by ClusterM** [comment] 2022-02-13 14:15
Please try the version 1.2. I also updated my server to 2022.2 and tested it for a while.

**Comment by HepoH3** [comment] 2022-02-14 05:38
> Please try the version 1.2. I also updated my server to 2022.2 and tested it for a while.

There is no wanings at first. But after the night following apeared:

> skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 99: self._child = pexpect.spawn("gatttool", ['-I', '-t', 'random', '-b', self._mac], timeout=KettleConnection.BLE_TIMEOUT)
> 
> skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 56: await self.hass.async_add_executor_job(self._child.sendline, data)

Also I noticed that I need to disconnect/reconnect my bluetooth dongle about few times a day. I'll try to switch back to earlier versions. If I remember correct, in past there was no such problem (I needed to reconnect dongl but no so frequent).

**Comment by HepoH3** [comment] 2022-02-17 06:10
After few days and core updates I can say that there is far more less warnings for now. But I have repeated times error with following message:

> Can't terminate, error (TypeError): async_add_executor_job() got an unexpected keyword argument 'force'
> Source: custom_components/skykettle/kettle_connection.py:140

**Comment by ClusterM** [comment] 2022-02-18 11:21
> After few days and core updates I can say that there is far more less warnings for now. But I have repeated times error with following message:
> 
> > Can't terminate, error (TypeError): async_add_executor_job() got an unexpected keyword argument 'force'
> > Source: custom_components/skykettle/kettle_connection.py:140

Fixed in the latest commit, thank you.

**Closed** 2022-02-23 14:35 UTC
Labels: bug, enhancement

**Comment by HepoH3** [comment] 2022-08-07 09:23
It's started again:

> Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 116: if self._child and self._child.isalive():
> Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 64: await self.hass.async_add_executor_job(self._child.sendcontrol, data)

Maybe it's kinda connected to new bluetooth integration from HA 2022.08, dunno.

**Comment by ClusterM** [comment] 2022-08-11 11:14
> doing blocking calls at custom_components/skykettle/kettle_connection.py, line 64: await self.hass.async_add_executor_job(self._child.sendcontrol, data)

But it's async call, it can't block by design...

**Comment by HepoH3** [comment] 2022-08-12 16:19
I think that thing with blocking calls sometimes have a false alarms, or we don't understand something.

**Comment by ClusterM** [comment] 2022-08-13 09:51
Version from master uses totally new Bluetooth API, so those methods are removed anyway.
